force-app/main/default/objects/Bypass_Configuration__c/Bypass_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Bypass Configuration</label>
</CustomObject>

force-app/main/default/objects/Bypass_Configuration__c/fields/Opportunity_Validation_Rule__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Validation_Rule__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Opportunity Validation Rule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reseller__c.field-meta.xml
<CustomField>
    <fullName>Reseller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reseller</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Reseller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reseller Opportunities</relationshipLabel>
    <relationshipName>ResellerOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TECH_Account_Partner_Status_Formula__c.field-meta.xml
<CustomField>
    <fullName>TECH_Account_Partner_Status_Formula__c</fullName>
    <formula>TEXT(Account.Partner_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Partner Status Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Price_Book_Automation__c/Price_Book_Automation__c.object-meta.xml
<CustomObject>
    <label>Price Book Automation</label>
    <nameField>
        <displayFormat>Auto-{00000}</displayFormat>
        <label>Automation Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Book Automations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_Book_Automation__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price_Book_Automation__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipName>Pricebooks_Automation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price_Book_Automation__c/fields/Reseller__c.field-meta.xml
<CustomField>
    <fullName>Reseller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reseller</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Reseller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Price Book Automations</relationshipLabel>
    <relationshipName>Price_Book_Automations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Allow_Pricebook_update_on_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Allow_Pricebook_update_on_Opportunity__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allow Pricebook update on Opportunity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Channel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Web - Update</fullName>
    </customValue>
    <customValue>
        <fullName>OEM</fullName>
        <isActive>false</isActive>
        <label>OEM</label>
    </customValue>
    <customValue>
        <fullName>Wholesaler/Distributor</fullName>
        <isActive>false</isActive>
        <label>Wholesaler/Distributor</label>
    </customValue>
    <customValue>
        <fullName>PAR</fullName>
        <isActive>false</isActive>
        <label>PAR</label>
    </customValue>
    <customValue>
        <fullName>OSI</fullName>
        <isActive>false</isActive>
        <label>OSI</label>
    </customValue>
    <customValue>
        <fullName>OSGE</fullName>
        <isActive>false</isActive>
        <label>OSGE</label>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
        <isActive>false</isActive>
        <label>AR</label>
    </customValue>
    <customValue>
        <fullName>OSCH</fullName>
        <isActive>false</isActive>
        <label>OSCH</label>
    </customValue>
    <customValue>
        <fullName>Internal</fullName>
        <isActive>false</isActive>
        <label>Internal</label>
    </customValue>
    <customValue>
        <fullName>Business Development</fullName>
        <isActive>false</isActive>
        <label>Business Development</label>
    </customValue>
    <customValue>
        <fullName>Research</fullName>
        <isActive>false</isActive>
        <label>Research</label>
    </customValue>
    <customValue>
        <fullName>OSME</fullName>
        <isActive>false</isActive>
        <label>OSME</label>
    </customValue>
    <customValue>
        <fullName>System Integrator</fullName>
        <isActive>false</isActive>
        <label>Systems Integrator</label>
    </customValue>
    <customValue>
        <fullName>Ecomm</fullName>
        <isActive>false</isActive>
        <label>E-commerce</label>
    </customValue>
    <masterLabel>Channel</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Market.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Academia</fullName>
    </customValue>
    <customValue>
        <fullName>Cannabis</fullName>
    </customValue>
    <customValue>
        <fullName>Ornamental</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Produce</fullName>
    </customValue>
    <customValue>
        <fullName>Research</fullName>
    </customValue>
    <customValue>
        <fullName>OSGE</fullName>
        <isActive>false</isActive>
        <label>OSGE</label>
    </customValue>
    <customValue>
        <fullName>OSCH</fullName>
        <isActive>false</isActive>
        <label>OSCH</label>
    </customValue>
    <customValue>
        <fullName>Hemp</fullName>
        <isActive>false</isActive>
        <label>Hemp</label>
    </customValue>
    <customValue>
        <fullName>OSI</fullName>
        <isActive>false</isActive>
        <label>OSI</label>
    </customValue>
    <customValue>
        <fullName>Ecommerce</fullName>
        <isActive>false</isActive>
        <label>Ecommerce</label>
    </customValue>
    <customValue>
        <fullName>Authorized Reseller</fullName>
        <isActive>false</isActive>
        <label>Authorized Reseller</label>
    </customValue>
    <customValue>
        <fullName>Comm Ag - Ornamental</fullName>
        <isActive>false</isActive>
        <label>Comm Ag - Ornamental</label>
    </customValue>
    <customValue>
        <fullName>Comm Ag - Produce</fullName>
        <isActive>false</isActive>
        <label>Comm Ag - Produce</label>
    </customValue>
    <customValue>
        <fullName>OSME</fullName>
        <isActive>false</isActive>
        <label>OSME</label>
    </customValue>
    <masterLabel>Market</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Americas-NA</fullName>
    </customValue>
    <customValue>
        <fullName>Americas-LATAM</fullName>
    </customValue>
    <customValue>
        <fullName>APAC</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA</fullName>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpportunityBO.cls
/**
*	@Author: Allan Pecli
*	@Company: HCL Technologies
*	@Class: Helper class for Opportunity Line Item's Business Object actions.
*	@Comments: Actually responsible to automatically assign the pricebook basing on the parameters.
*	@Created Date: 07/12/2021
*
*	------------------------------------------------------------------------------------------
*	Modification Log:
*	==========================================================================================
*	@Version		@Author			@Date			@Reason 
*	==========================================================================================
*/
public class OpportunityBO {
    /*---------------------------------------------------------------------------------------------------------------------------
* Author: Allan Pecli
* Method Description: Automatically assignment of the pricebook basing on the Reseller / parameters.
* CreatedDate: July 26, 2021
* Modification Comments:
-----------------------------------------------------------------------------------------------------------------------------*/
    public static void automaticallyAssignPriceBook(List<Opportunity> lstOpportunities)
    {
        Set<String> channelValues = new Set<String>(); 
        Set<String> regionValues = new Set<String>();
        Set<String> partnerStatusValues = new Set<String>();
        Set<String> marketValues = new Set<String>();         
        Set<String> currencyIsoCodes = new Set<String>();
        Set<Id> resellerIds = new Set<Id>();
        Map<String,Price_Book_Automation__c> pricebookAutomations = new Map<String,Price_Book_Automation__c>();
        Boolean allowPricebookUpdate = [Select Allow_Pricebook_update_on_Opportunity__c From User Where Id = :UserInfo.getUserId()][0].Allow_Pricebook_update_on_Opportunity__c;
        
        for(Opportunity opp : lstOpportunities){
            if( opp.Pricebook2Id != null && !Bypass_Configuration__c.getInstance(UserInfo.getUserId()).Opportunity_Validation_Rule__c && !allowPricebookUpdate){
                opp.AddError(Label.Opportunity_Pricebook_on_creation_error_message);
            }else{
                resellerIds.add(opp.Reseller__c);
                channelValues.add(opp.Channel__c);
                regionValues.add(opp.Region__c);
                partnerStatusValues.add(opp.TECH_Account_Partner_Status_Formula__c);
                marketValues.add(opp.Market__c);
                currencyIsoCodes.add(opp.currencyIsoCode);
            }
        }
            pricebookAutomations = PricebookAutomationDAO.getInstance().getPricebookAutomationMapInfobyParameters(resellerIds, channelValues, regionValues, marketValues,partnerStatusValues, currencyIsoCodes);

        if(!pricebookAutomations.isEmpty()){
        for(Opportunity opp : lstOpportunities){
            if(opp.Reseller__c != null && pricebookAutomations.containsKey(String.valueOf(opp.Reseller__c )))
            {
                opp.Pricebook2Id = pricebookAutomations.get(String.valueOf(opp.Reseller__c )).Price_Book__c;
            }
            else
            {
                if(pricebookAutomations.containsKey(String.ValueOf(opp.Channel__c)+String.valueOf(opp.Region__c)+String.valueOf(opp.Market__c)+String.valueOf(opp.TECH_Account_Partner_Status_Formula__c)+opp.currencyIsoCode)){
                    opp.Pricebook2Id = pricebookAutomations.get(String.ValueOf(opp.Channel__c)+String.valueOf(opp.Region__c)+String.valueOf(opp.Market__c)+String.valueOf(opp.TECH_Account_Partner_Status_Formula__c)+opp.currencyIsoCode).Price_Book__c;
                }
            }            
        } 
    }
}
}