force-app/main/default/objects/Product_Discount__c/Product_Discount__c.object-meta.xml
<CustomObject>
    <label>Product Discount</label>
    <nameField>
        <displayFormat>Disc-{00000000}</displayFormat>
        <label>Dicount Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Discount__c/fields/Fifth_Range__c.field-meta.xml
<CustomField>
    <fullName>Fifth_Range__c</fullName>
    <label>5th Range</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Discount__c/fields/Fifth_Range_Value__c.field-meta.xml
<CustomField>
    <fullName>Fifth_Range_Value__c</fullName>
    <label>5th Range Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Discount__c/fields/First_Range__c.field-meta.xml
<CustomField>
    <fullName>First_Range__c</fullName>
    <label>1st Range</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Discount__c/fields/First_Range_Value__c.field-meta.xml
<CustomField>
    <fullName>First_Range_Value__c</fullName>
    <label>1st Range Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Discount__c/fields/Fourth_Range__c.field-meta.xml
<CustomField>
    <fullName>Fourth_Range__c</fullName>
    <label>4th Range</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Discount__c/fields/Fourth_Range_Value__c.field-meta.xml
<CustomField>
    <fullName>Fourth_Range_Value__c</fullName>
    <label>4th Range Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Discount__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Product Discounts</relationshipLabel>
    <relationshipName>Product_Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Discount__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Discounts</relationshipLabel>
    <relationshipName>Product_Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Discount__c/fields/Second_Range__c.field-meta.xml
<CustomField>
    <fullName>Second_Range__c</fullName>
    <label>2nd Range</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Discount__c/fields/Second_Range_Value__c.field-meta.xml
<CustomField>
    <fullName>Second_Range_Value__c</fullName>
    <label>2nd Range Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Discount__c/fields/Sixth_Range_Value__c.field-meta.xml
<CustomField>
    <fullName>Sixth_Range_Value__c</fullName>
    <label>6th Range Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Discount__c/fields/Third_Range__c.field-meta.xml
<CustomField>
    <fullName>Third_Range__c</fullName>
    <label>3rd Range</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Discount__c/fields/Third_Range_Value__c.field-meta.xml
<CustomField>
    <fullName>Third_Range_Value__c</fullName>
    <label>3rd Range Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ProductDiscountDAO.cls
/**
*	@Author: Allan Pecli
*	@Company: HCL Technologies
*	@Class: Data class for Product Discount's Object.
*	@Comments: 
*	@Created Date: 07/26/2021
*	@Version: 0.0
*
*	------------------------------------------------------------------------------------------
*	Modification Log:
*	==========================================================================================
*	@Version		@Author			@Date			@Reason 
*	==========================================================================================
*/
public class ProductDiscountDAO {
    private static final ProductDiscountDAO instance = new ProductDiscountDAO();    
    private ProductDiscountDAO(){}
    
    public static ProductDiscountDAO getInstance() {
        return instance;
    }
    /*---------------------------------------------------------------------------------------------------------------------------
* Author: Allan Pecli
* Method Description: Retrieve the Product Discount Map with ID = Product__c + Price_Book__c + CurrencyIsoCode
* CreatedDate: July 26, 2021
* Modification Comments:
-----------------------------------------------------------------------------------------------------------------------------*/
    public Map<String,Product_Discount__c> getProductDiscountMapInfobyParameters(Set<Id> productIds, Set<Id> pricebookIds, Set<String> currencyIsoCodes)
    {
        Map<String,Product_Discount__c> mapProductDiscount = new Map<String,Product_Discount__c>();
        For(Product_Discount__c productDisc : [SELECT Id, Product__c, Price_Book__c, CurrencyIsoCode, First_Range__c, First_Range_Value__c, Second_Range__c, Second_Range_Value__c, Third_Range__c, Third_Range_Value__c, Fourth_Range__c, Fourth_Range_Value__c, Fifth_Range__c, Fifth_Range_Value__c, Sixth_Range_Value__c FROM Product_Discount__c WHERE Product__c IN:productIds AND Price_Book__c IN:pricebookIds AND CurrencyIsoCode IN:currencyIsoCodes ]){
            mapProductDiscount.put(String.valueOf(productDisc.Product__c) + String.valueOf(productDisc.Price_Book__c).left(15) + productDisc.CurrencyIsoCode,productDisc);
        }
        if(!mapProductDiscount.IsEmpty()){
            return mapProductDiscount;
        }else{
            return new Map<String,Product_Discount__c>();
        }
    }
}