force-app/main/default/objects/Error_Log__c/fields/Error_Log_Details__c.field-meta.xml
<CustomField>
    <fullName>Error_Log_Details__c</fullName>
    <label>Error Log Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ApplicationErrorLog.cls
public class ApplicationErrorLog {
  
    private String error;
    private String obj;
    private String stackTrace;
    private String shortError;
    private Id userId;
  
  
    public System.Exception exceptionObj;

    private Error_Log__c applicationLog;

    public Error_Log__c getApplicationLog() {
        if (applicationLog == null) {
            applicationLog = new Error_Log__c(
                Error_Log_Details__c = getError(),
                Object__c = getObject(),
                Stack_Trace__c = getStackTrace(),
                User__c = getUserId()             
            );
        }
        return applicationLog;
    }
    
    
    private String getShortError() {
        if (exceptionObj != null) {
            shortError = exceptionObj.getTypeName() + ':' + exceptionObj.getMessage();
        }
        return shortError;
    }

    private String getError() {
        if (error == null && exceptionObj != null) {
            error = getShortError();
        }
        return error.left(131000);
    }



    private String getObject() {
        return obj;
    }

    private String getStackTrace() {
        if (stackTrace == null) {
            if (exceptionObj != null) {
                stackTrace = exceptionObj.getStackTraceString();
            } else {
                stackTrace = new DmlException().getStackTraceString();
            }
        }
        return stackTrace;
    }

   

    private Id getUserId() {
        if (userId == null) {
            userId = UserInfo.getUserId();
        }
        return userId;
    }
  
}