force-app/main/default/objects/Case/fields/Date_when_first_time_submitted__c.field-meta.xml
<CustomField>
    <fullName>Date_when_first_time_submitted__c</fullName>
    <label>Date when first time submitted</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/First_LDRF_Designer__c.field-meta.xml
<CustomField>
    <fullName>First_LDRF_Designer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>First LDRF Designer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CasesLDRFDesigner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Is_FAE_Review_complete__c.field-meta.xml
<CustomField>
    <fullName>Is_FAE_Review_complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is FAE Review complete?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Is_FAE_Review_rejected__c.field-meta.xml
<CustomField>
    <fullName>Is_FAE_Review_rejected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is FAE Review  rejected?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/LDRF_Auto_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>LDRF_Auto_Close_Date__c</fullName>
    <label>LDRF Auto Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Opp_Prob_when_LDRF_submitted__c.field-meta.xml
<CustomField>
    <fullName>Opp_Prob_when_LDRF_submitted__c</fullName>
    <label>Opp Prob % when LDRF submitted</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Case/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>RARF, LDRF and HS Cases</relationshipLabel>
    <relationshipName>RARFandLDRFCases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Submit_case__c.field-meta.xml
<CustomField>
    <fullName>Submit_case__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>First click on &quot;Edit&quot; button, and then check this field to submit LDRF.</inlineHelpText>
    <label>Submit LDRF</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/LDRF.recordType-meta.xml
<RecordType>
    <fullName>LDRF</fullName>
    <active>true</active>
    <businessProcess>LDRF</businessProcess>
    <description>Lighting Design Request Form</description>
    <label>LDRF</label>
</RecordType>

force-app/main/default/classes/submitLDRFController.cls
/**
*	@Author: Vartika Rai
*	@Company: HCL Technologies
*	@Class: Consists of methods to submit LDRF Case and trigger Case Assignment rules
*	@Comments: 
*	@Created Date: 10/20/2021
*	@Version: 0.0
*
*	------------------------------------------------------------------------------------------
*	Modification Log:
*	==========================================================================================
*	@Version		@Author			@Date			@Reason 
*	==========================================================================================
*/
public class submitLDRFController {
    
    @AuraEnabled 
    public static boolean submitLDRFCase(Id recordId)	
    {
        Boolean isSuccess;
        //Fetching the assignment rules on case
        AssignmentRule AR = new AssignmentRule();
        AR = [select id from AssignmentRule where SobjectType = 'Case' and Active = true limit 1];
        
        //Creating the DMLOptions for "Assign using active assignment rules" checkbox
        Database.DMLOptions dmlOpts = new Database.DMLOptions();
        dmlOpts.assignmentRuleHeader.assignmentRuleId= AR.id;
        
        Case caseToBeSubmitted = [Select Id,Status,Submit_case__c,Is_FAE_Review_rejected__c,Is_FAE_Review_complete__c,RecordTypeId, Opportunity__r.Probability, Opp_Prob_when_LDRF_submitted__c, OwnerId, First_LDRF_Designer__c from case where Id =: recordId] ;
        //Setting the DMLOption on Case instance
        if(String.valueOf(caseToBeSubmitted.RecordTypeId).contains(Label.LDRF)){
            If(!Label.LDRFCaseStatusToPreventSubmission.contains(caseToBeSubmitted.Status)){
                if(Label.LDRFCaseStatusToChangeToSubmitted.contains(caseToBeSubmitted.Status)){
                    if(caseToBeSubmitted.Opp_Prob_when_LDRF_submitted__c == null || caseToBeSubmitted.Opp_Prob_when_LDRF_submitted__c == 0){
                        caseToBeSubmitted.Opp_Prob_when_LDRF_submitted__c = caseToBeSubmitted.Opportunity__r.Probability;
                        caseToBeSubmitted.Date_when_first_time_submitted__c = system.today();
                    } 
                    if(String.isBlank(caseToBeSubmitted.First_LDRF_Designer__c) && String.valueOf(caseToBeSubmitted.OwnerId).left(3) != '00G'){
                        caseToBeSubmitted.First_LDRF_Designer__c = caseToBeSubmitted.OwnerId;
                    }
                  
                    if(Label.LDRFCaseStatusToChangeToUrgentPriorityOnSubmission.contains(caseToBeSubmitted.Status) && caseToBeSubmitted.Is_FAE_Review_rejected__c){
   
                        caseToBeSubmitted.Priority = 'Urgent';
                        caseToBeSubmitted.Status = 'Submitted';

                    }else if(!Label.LDRFCaseStatusToChangeToUrgentPriorityOnSubmission.contains(caseToBeSubmitted.Status)){
                        if(Label.LDRFCaseStatusToChangeToHighPriorityOnSubmission.contains(caseToBeSubmitted.Status)){
                            caseToBeSubmitted.Priority = 'High';
                            caseToBeSubmitted.LDRF_Auto_Close_Date__c = Util.addBussinessDays(system.today(),10);
                        }
                        caseToBeSubmitted.Status = 'Submitted';    
                    }           
                    caseToBeSubmitted.Is_FAE_Review_rejected__c = FALSE;
                }
                caseToBeSubmitted.Submit_case__c = true;
                caseToBeSubmitted.setOptions(dmlOpts);
                Database.SaveResult sr = Database.update(caseToBeSubmitted, false);
                isSuccess = sr.isSuccess() ? true: false;
            } else{
                isSuccess = false;
            }
        } 
        return isSuccess;
    }
}