force-app/main/default/objects/Application_Log__c/Application_Log__c.object-meta.xml
<CustomObject>
    <label>Application Log</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Application Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application_Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Log__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Changed Field</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Log__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <label>Object Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ApplicationLogException.cls
/**
 * Created by Barbara Neves on 16/04/2022.
 */

public class ApplicationLogException extends Exception {  
 
    private  Application_Log__c applicationLog;
  
    public Application_Log__c createApplicationLog(String object_Name,String field,String prior_Value,String new_Value,String recordID) {
       
        applicationLog = new Application_Log__c(         
            Object_Name__c = object_Name,
            Field__c = field,
            Record_ID__c = recordID,
            Old_Value__c = prior_Value,
            New_Value__c = new_Value

        );
        
        return applicationLog;
    }

  
}