force-app/main/default/objects/Application_Log__c/Application_Log__c.object-meta.xml
<CustomObject>
    <label>Application Log</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Application Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application_Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application_Log__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Changed Field</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Application_Log__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <label>Object Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ApplicationLogWrapper_Test.cls
/**
 * Created by Barbara Neves on 16/04/2022.
 */

@IsTest
private class ApplicationLogWrapper_Test {
   @IsTest
    static void testApplicationLogCreation() {

        Application_Log__c appLog;
        ApplicationLogWrapper logWrapper = new ApplicationLogWrapper();
        appLog = logWrapper.createApplicationLog('Quote','Amount','38.0','40.2','a0V05000000sUaaEAE');
        System.assertEquals(appLog.Object_Name__c,'Quote');
        System.assertEquals(appLog.Field__c,'Amount');
        System.assertEquals(appLog.Old_Value__c,'38.0');
        System.assertEquals(appLog.New_Value__c,'40.2');
        System.assertEquals(appLog.Record_ID__c,'a0V05000000sUaaEAE');

      
    }
}