force-app/main/default/objects/SPAM_Email__c/SPAM_Email__c.object-meta.xml
<CustomObject>
    <label>SPAM Email</label>
    <nameField>
        <displayFormat>SPAM-{0000}</displayFormat>
        <label>SPAM Email Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SPAM Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPAM_Email__c/fields/Sources_to_Block__c.field-meta.xml
<CustomField>
    <fullName>Sources_to_Block__c</fullName>
    <label>Sources to Block</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Email To Case</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SpamEmailDAO.cls
/**
*	@Author: Vartika Rai
*	@Company: HCL Technologies
*	@Class: Data class for Spam Email Object.
*	@Comments: 
*	@Created Date: 10/11/2021
*	@Version: 0.0
*
*	------------------------------------------------------------------------------------------
*	Modification Log:
*	==========================================================================================
*	@Version		@Author			@Date			@Reason 
*	==========================================================================================
*/
public class SpamEmailDAO {
    private static final SpamEmailDAO instance = new SpamEmailDAO();    
    private SpamEmailDAO(){}
    
    public static SpamEmailDAO getInstance() {
        return instance;
    }
    public Map<String,String>  getSpamEmails()
    {
        Map<String,String> spamEmailsMap = new Map<String,String>();
        for(SPAM_Email__c s : [SELECT Id, Name, Email_ID__c,Sources_to_Block__c from SPAM_Email__c])
        {
            spamEmailsMap.put(s.Email_ID__c,s.Sources_to_Block__c);
        }
        return !spamEmailsMap.isEmpty() ? spamEmailsMap : new Map<String,String>();       
    }
}