force-app/main/default/objects/Account/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Application</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Account Channel</description>
    <label>Channel</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Account Market</description>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Partner_Status__c.field-meta.xml
<CustomField>
    <fullName>Partner_Status__c</fullName>
    <label>Partner Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Channel__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Partner_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Account Region</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Account Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Contact_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Reseller__c.field-meta.xml
<CustomField>
    <fullName>Reseller__c</fullName>
    <formula>Opportunity__r.Reseller__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reseller</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/General.recordType-meta.xml
<RecordType>
    <fullName>General</fullName>
    <active>true</active>
    <businessProcess>General</businessProcess>
    <description>General Cases</description>
    <label>General</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Application</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CapEx</fullName>
            </value>
            <value>
                <fullName>Terms</fullName>
            </value>
            <value>
                <fullName>Technical Features</fullName>
            </value>
            <value>
                <fullName>Portfolio Gap</fullName>
            </value>
            <value>
                <fullName>Relationships/Politics</fullName>
            </value>
            <value>
                <fullName>Quality Issues</fullName>
            </value>
            <value>
                <fullName>Late Entry</fullName>
            </value>
            <value>
                <fullName>Lack of LED Experience</fullName>
            </value>
            <value>
                <fullName>Lack of Reference</fullName>
            </value>
            <value>
                <fullName>Warranty</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>No License</fullName>
            </value>
            <value>
                <fullName>Lost Facility/Property</fullName>
            </value>
            <value>
                <fullName>Lost Budget/Financing</fullName>
            </value>
            <value>
                <fullName>No Response</fullName>
            </value>
            <value>
                <fullName>Postponed</fullName>
            </value>
            <value>
                <fullName>Salesmanship</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Brand</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Financing</fullName>
            </value>
            <value>
                <fullName>Product/Product Feature(s)</fullName>
            </value>
            <value>
                <fullName>Horticulture Services</fullName>
            </value>
            <value>
                <fullName>Rebate Services</fullName>
            </value>
            <value>
                <fullName>Solution Architects</fullName>
            </value>
            <value>
                <fullName>Relationship/Consultant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reseller__c.field-meta.xml
<CustomField>
    <fullName>Reseller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reseller</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Reseller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reseller Opportunities</relationshipLabel>
    <relationshipName>ResellerOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Opportunity Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Won</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Received PO</fullName>
                <isActive>false</isActive>
                <label>Received PO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price_Book_Automation__c/Price_Book_Automation__c.object-meta.xml
<CustomObject>
    <label>Price Book Automation</label>
    <nameField>
        <displayFormat>Auto-{00000}</displayFormat>
        <label>Automation Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Book Automations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_Book_Automation__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price_Book_Automation__c/fields/Partner_Status__c.field-meta.xml
<CustomField>
    <fullName>Partner_Status__c</fullName>
    <label>Partner Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Partner_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price_Book_Automation__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipName>Pricebooks_Automation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price_Book_Automation__c/fields/Reseller__c.field-meta.xml
<CustomField>
    <fullName>Reseller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reseller</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Reseller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Price Book Automations</relationshipLabel>
    <relationshipName>Price_Book_Automations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Discount__c/Product_Discount__c.object-meta.xml
<CustomObject>
    <label>Product Discount</label>
    <nameField>
        <displayFormat>Disc-{00000000}</displayFormat>
        <label>Dicount Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Discount__c/fields/First_Range__c.field-meta.xml
<CustomField>
    <fullName>First_Range__c</fullName>
    <label>1st Range</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Discount__c/fields/First_Range_Value__c.field-meta.xml
<CustomField>
    <fullName>First_Range_Value__c</fullName>
    <label>1st Range Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Discount__c/fields/Fourth_Range__c.field-meta.xml
<CustomField>
    <fullName>Fourth_Range__c</fullName>
    <label>4th Range</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Discount__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Product Discounts</relationshipLabel>
    <relationshipName>Product_Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Discount__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Discounts</relationshipLabel>
    <relationshipName>Product_Discounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Discount__c/fields/Second_Range__c.field-meta.xml
<CustomField>
    <fullName>Second_Range__c</fullName>
    <label>2nd Range</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Discount__c/fields/Second_Range_Value__c.field-meta.xml
<CustomField>
    <fullName>Second_Range_Value__c</fullName>
    <label>2nd Range Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Discount__c/fields/Third_Range__c.field-meta.xml
<CustomField>
    <fullName>Third_Range__c</fullName>
    <label>3rd Range</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Discount__c/fields/Third_Range_Value__c.field-meta.xml
<CustomField>
    <fullName>Third_Range_Value__c</fullName>
    <label>3rd Range Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Reseller__c.field-meta.xml
<CustomField>
    <fullName>Reseller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reseller</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reseller Quotes</relationshipLabel>
    <relationshipName>ResellerQuotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Temporary_Address__c.field-meta.xml
<CustomField>
    <fullName>Temporary_Address__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Temporary Address?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/SAPQuoteLineItem__c.field-meta.xml
<CustomField>
    <fullName>SAPQuoteLineItem__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox that informs that Quote Line Item is from SAP system.</description>
    <label>SAP Quote Line Item</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Allow_Pricebook_update_on_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Allow_Pricebook_update_on_Opportunity__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allow Pricebook update on Opportunity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Account_Contact_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
    </customValue>
    <customValue>
        <fullName>Purge</fullName>
    </customValue>
    <masterLabel>Account Contact Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Application.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Greenhouse</fullName>
    </customValue>
    <customValue>
        <fullName>Indoor</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Application</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Channel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Web - Update</fullName>
    </customValue>
    <customValue>
        <fullName>OEM</fullName>
        <isActive>false</isActive>
        <label>OEM</label>
    </customValue>
    <customValue>
        <fullName>Wholesaler/Distributor</fullName>
        <isActive>false</isActive>
        <label>Wholesaler/Distributor</label>
    </customValue>
    <customValue>
        <fullName>PAR</fullName>
        <isActive>false</isActive>
        <label>PAR</label>
    </customValue>
    <customValue>
        <fullName>OSI</fullName>
        <isActive>false</isActive>
        <label>OSI</label>
    </customValue>
    <customValue>
        <fullName>OSGE</fullName>
        <isActive>false</isActive>
        <label>OSGE</label>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
        <isActive>false</isActive>
        <label>AR</label>
    </customValue>
    <customValue>
        <fullName>OSCH</fullName>
        <isActive>false</isActive>
        <label>OSCH</label>
    </customValue>
    <customValue>
        <fullName>Internal</fullName>
        <isActive>false</isActive>
        <label>Internal</label>
    </customValue>
    <customValue>
        <fullName>Business Development</fullName>
        <isActive>false</isActive>
        <label>Business Development</label>
    </customValue>
    <customValue>
        <fullName>Research</fullName>
        <isActive>false</isActive>
        <label>Research</label>
    </customValue>
    <customValue>
        <fullName>OSME</fullName>
        <isActive>false</isActive>
        <label>OSME</label>
    </customValue>
    <customValue>
        <fullName>System Integrator</fullName>
        <isActive>false</isActive>
        <label>Systems Integrator</label>
    </customValue>
    <customValue>
        <fullName>Ecomm</fullName>
        <isActive>false</isActive>
        <label>E-commerce</label>
    </customValue>
    <masterLabel>Channel</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Market.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Academia</fullName>
    </customValue>
    <customValue>
        <fullName>Cannabis</fullName>
    </customValue>
    <customValue>
        <fullName>Ornamental</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Produce</fullName>
    </customValue>
    <customValue>
        <fullName>Research</fullName>
    </customValue>
    <customValue>
        <fullName>OSGE</fullName>
        <isActive>false</isActive>
        <label>OSGE</label>
    </customValue>
    <customValue>
        <fullName>OSCH</fullName>
        <isActive>false</isActive>
        <label>OSCH</label>
    </customValue>
    <customValue>
        <fullName>Hemp</fullName>
        <isActive>false</isActive>
        <label>Hemp</label>
    </customValue>
    <customValue>
        <fullName>OSI</fullName>
        <isActive>false</isActive>
        <label>OSI</label>
    </customValue>
    <customValue>
        <fullName>Ecommerce</fullName>
        <isActive>false</isActive>
        <label>Ecommerce</label>
    </customValue>
    <customValue>
        <fullName>Authorized Reseller</fullName>
        <isActive>false</isActive>
        <label>Authorized Reseller</label>
    </customValue>
    <customValue>
        <fullName>Comm Ag - Ornamental</fullName>
        <isActive>false</isActive>
        <label>Comm Ag - Ornamental</label>
    </customValue>
    <customValue>
        <fullName>Comm Ag - Produce</fullName>
        <isActive>false</isActive>
        <label>Comm Ag - Produce</label>
    </customValue>
    <customValue>
        <fullName>OSME</fullName>
        <isActive>false</isActive>
        <label>OSME</label>
    </customValue>
    <masterLabel>Market</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Partner_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Signed</fullName>
    </customValue>
    <customValue>
        <fullName>Unsigned</fullName>
    </customValue>
    <masterLabel>Partner Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Americas-NA</fullName>
    </customValue>
    <customValue>
        <fullName>Americas-LATAM</fullName>
    </customValue>
    <customValue>
        <fullName>APAC</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA</fullName>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestDataFactory.cls
/**
*	@Author: Vartika Rai
*	@Company: HCL Technologies
*	@Class: TestDataFactory class
*	@Comments: consists of methods to create Test Data
*	@Created Date: 07/22/2021
*	@Version: 0.0
*
*	------------------------------------------------------------------------------------------
*	Modification Log:
*	==========================================================================================
*	@Version		@Author			@Date			@Reason
*	-              Lucas Silva     11/01/2024      Changed createQuoteLineItems() adding SAPQuoteLineItem__c = true
*	-              Lucas Silva     25/01/2024      Remove createAIRecord() method
*	==========================================================================================
*/
@isTest
public class TestDataFactory {
    
    /**
     * *******************************************************
     * This method is to create test data for SYS ADMIN USER
     * *******************************************************
     */
    public static User createUser()
    {
        String uniqueUserName = 'standardadmin' + DateTime.now().getTime() + '@testorg.com';
        // This code runs as the system user
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com',
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
        LocaleSidKey='en_US', ProfileId = p.Id,
        TimeZoneSidKey='America/Los_Angeles',
         UserName=uniqueUserName,Allow_Pricebook_update_on_Opportunity__c=true);
        insert u;
        return u;
    }
    
    /**
     * *******************************************************
     * This method is to create test data for ACCOUNT object
     * *******************************************************
     */
    public static List<Account> createAccounts(Integer count,Boolean doInsert)
    {
        List<Account> accList = new List<Account>();
        System.runAs(createUser())
        {
           
            for(Integer i = 0 ; i < count ; i++)
            {
                Account acc = new Account();
                acc.Name = 'Test Account+++ '+i;
                acc.Region__c = 'APAC';
                acc.Application__c = 'Indoor';
                acc.Channel__c = 'System Integrator';
                acc.Market__c = 'Cannabis';
                acc.Partner_Status__c = 'Signed';
                acc.BillingCountry = 'United States';
                acc.BillingCity = 'New York';
                acc.BillingState = 'New York';
                acc.BillingPostalCode = '94085';
                acc.BillingStreet = 'Test Street';
                acc.ShippingCountryCode = 'US';
                acc.ShippingCountry = 'United States'; 
                acc.ShippingCity = 'Austin'; 
                acc.ShippingPostalCode = '78744'; 
                acc.ShippingState = 'Texas'; 
                acc.ShippingStreet = '4129 Commercial Center Drive'; 
                acc.ShippingStateCode = 'TX';
                accList.add(acc);
            }
            if(doInsert){
                insert accList;
            }            
        } 
        return accList; 
    }
    
    /**
     * ************************************************************
     * These methods are to create test data for CONTACT object
     * ************************************************************
     */
    public static List<Contact> createContacts(Integer count,Boolean doInsert)
    {
        List<Account> accList = createAccounts(count,true);
        List<Contact> contactList = new List<Contact>();
        System.runAs(createUser())
        {
           for(Integer i = 0 ; i < count ; i++)
            {
                Contact con = new Contact();
                con.FirstName = 'Test';
                con.LastName = 'contact'+i;
                con.AccountId = accList[i].Id;
                con.Email = con.LastName+'@abc.com';
                con.Phone = '99999999';
                contactList.add(con);
            }
            if(doInsert){
                insert contactList;
            } 
        }        
        return contactList;
    } 
    
	public static List<Contact> createContacts(Integer count,Boolean doInsert,Id accId)
    {
        List<Contact> contactList = new List<Contact>();
        System.runAs(createUser())
        {
            for(Integer i = 0 ; i < count ; i++)
            {
                Contact con = new Contact();
                con.FirstName = 'Test';
                con.LastName = 'contact'+i;
                con.AccountId = accId;
                con.Email = con.LastName+'@abc.com';
                con.Phone = '99999999';
                contactList.add(con);
            }
            if(doInsert){
                insert contactList;
            }
        }        
        return contactList;
    }
    
    /**
     * *****************************************************************
     * These methods are to create test data for OPPORTUNITY object
     * *****************************************************************
     */
    
    public static List<Opportunity> createOpportunities(Integer count,Boolean doInsert)
    {
        List<Account> accList = createAccounts(count,true);
        List<Opportunity> oppList = new List<Opportunity>();
        System.runAs(createUser())
        {
            for(Integer i = 0 ; i < count ; i++)
            {
                Opportunity opp = new Opportunity();
                opp.Name = 'Test Opportunity++++ '+i;
                opp.AccountId = accList[i].Id;
                opp.Amount = 3000;
                opp.StageName = 'Discovery';
                opp.CloseDate = Date.today();
                opp.currencyIsoCode = 'USD';
        		opp.Market__c = 'Cannabis';
                opp.Status__c = 'Open';
                opp.Region__c = 'EMEA';
                opp.Pricebook2Id = Test.getStandardPricebookId();
                opp.Application__c = 'Greenhouse';
                opp.Reason__c = ''; 
                oppList.add(opp);
            }
            if(doInsert){
                insert oppList;
            }
        }        
        return oppList;
    }
    
    public static List<Opportunity> createOpportunities(Integer count,Boolean doInsert,Id accId)
    {
        List<Opportunity> oppList = new List<Opportunity>();
        System.runAs(createUser())
        {
            for(Integer i = 0 ; i < count ; i++)
            {
                Opportunity opp = new Opportunity();
                opp.Name = 'Test Opportunity '+i;
                opp.AccountId = accId;
                opp.Amount = 3000;
                opp.StageName = 'Discovery';
                opp.CloseDate = Date.today();
                opp.currencyIsoCode = 'USD';
        		opp.Market__c = 'Cannabis';
                opp.Status__c = 'Open';
                opp.Region__c = 'EMEA';
                opp.Application__c = 'Greenhouse';
                opp.Pricebook2Id = Test.getStandardPricebookId();
               opp.Reason__c = '';
                oppList.add(opp);
            }
            if(doInsert){
                insert oppList;
            }
        }        
        return oppList;
    }
    
    public static List<Opportunity> createOpportunitiesWithResellers(Integer count,Boolean doInsert,Id accId, Id resellerId)
    {
        List<Opportunity> oppList = new List<Opportunity>();
        System.runAs(createUser())
        {
            for(Integer i = 0 ; i < count ; i++)
            {
                Opportunity opp = new Opportunity();
                opp.Name = 'Test Opportunity++ '+i;
                opp.AccountId = accId;
                opp.Amount = 3000;
                opp.StageName = 'Discovery';
                opp.CloseDate = Date.today();
                opp.currencyIsoCode = 'USD';
        		opp.Market__c = 'Cannabis';
                opp.Status__c = 'Open';
                opp.Region__c = 'EMEA';
                opp.Application__c = 'Greenhouse';
                opp.Reseller__c = resellerId;
                oppList.add(opp);
            }
            if(doInsert){
                insert oppList;
            }
        }        
        return oppList;
    }
    
    /**
    * *****************************************************************
    * These methods are to create test data for CASE object
    * *****************************************************************
    */
    public static List<Case> createCases(Integer count, Boolean doInsert, String contactId)
    {
        List<Case> caseList = new List<Case>();
        System.runAs(createUser())
        {
            for(Integer i = 0 ; i < count ; i++)
            {
                Case cas = new Case(ContactId = contactId, Status ='New', Priority = 'Medium', Origin = 'Email',Subject = 'Test Case '+i, recordtypeid=Schema.SObjectType.Case.getRecordTypeInfosByName().get('General').getRecordTypeId());
                caseList.add(cas);
            }
            if(doInsert)
            {
                insert caseList ;
            }
        }        
        return caseList ;
    } 
    
    /**
    * *****************************************************************
    * These methods are to create test data for QUOTE object
    * *****************************************************************
    */
    public static List<Quote> createQuotes(Integer count, Boolean doInsert)
    {
        List<Opportunity> oppList = createOpportunities(count, true);
        List<Quote> quotesList = new List<Quote>();
        System.runAs(createUser())
        {
            for(Integer i = 0 ; i < count ; i++)
            {
                Quote qt = new Quote(Name = 'Quote '+i, OpportunityId = oppList[i].Id, ShippingHandling = 2000, ShippingCountryCode = 'US', ShippingCountry = 'United States', ShippingCity = 'Austin', ShippingPostalCode = '78744', ShippingState = 'Texas', ShippingStreet = '4129 Commercial Center Drive', ShippingStateCode = 'TX', Temporary_Address__c = true);
                quotesList.add(qt);
            }
            if(doInsert)
            {
                insert quotesList ;
            }
        }        
        return quotesList ;
    }
    
    public static List<Quote> createQuotes(Integer count, Boolean doInsert, Id OppId)
    {
        List<Quote> quotesList = new List<Quote>();
        System.runAs(createUser())
        {
            for(Integer i = 0 ; i < count ; i++)
            {
                Quote qt = new Quote(Name = 'Quote '+i, OpportunityId = OppId, ShippingHandling = 2000, ShippingCountryCode = 'US', ShippingCountry = 'United States', ShippingCity = 'Austin', ShippingPostalCode = '78744', ShippingState = 'Texas', ShippingStreet = '4129 Commercial Center Drive', ShippingStateCode = 'TX', Temporary_Address__c = true);
                quotesList.add(qt);
            }
            if(doInsert)
            {
                insert quotesList ;
            }
        }        
        return quotesList ;
    }
    
    public static List<Quote> createQuotes(Integer count, Boolean doInsert, Id OppId, Id ConId)
    {
        List<Quote> quotesList = new List<Quote>();
        System.runAs(createUser())
        {
            for(Integer i = 0 ; i < count ; i++)
            {
                 	
                Quote qt = new Quote(Name = 'Quote '+i, ContactId = ConId, OpportunityId = OppId, ShippingHandling = 2000, ShippingCountryCode = 'US', ShippingCountry = 'United States', ShippingCity = 'Austin', ShippingPostalCode = '78744', ShippingState = 'Texas', ShippingStreet = '4129 Commercial Center Drive', ShippingStateCode = 'TX', Temporary_Address__c = true);
                quotesList.add(qt);
            }
            if(doInsert)
            {
                insert quotesList ;
            }
        }        
        return quotesList ;
    }
    
    /**
    * *****************************************************************
    * This method is to create test data for QUOTE LINE ITEM object
    * *****************************************************************
    */
    public static List<QuoteLineItem> createQuoteLineItems(Integer count, Boolean doInsert, Id qId)
    {
        List<QuoteLineItem> quotesLineItemsList = new List<QuoteLineItem>();
        System.runAs(createUser())
        {
            List<PricebookEntry> lstPricebookEntryToInsert = new List<PricebookEntry>();
            List<Product2> lstProductToInsert = new List<Product2>();
            Product2 pro = new Product2(Name = 'Test Product', Family = 'Mobile');
            lstProductToInsert.add(pro);
            
            pro = new Product2(Name = 'Surcharge', Family = 'Mobile');
            lstProductToInsert.add(pro);
            Insert lstProductToInsert;

            PricebookEntry pbe = new PricebookEntry(Pricebook2Id = Test.getStandardPricebookId(),Product2Id = lstProductToInsert[0].Id,UnitPrice = 1020,IsActive = true);
            lstPricebookEntryToInsert.add(pbe);
            
            pbe = new PricebookEntry(Pricebook2Id = Test.getStandardPricebookId(),Product2Id = lstProductToInsert[1].Id,UnitPrice = 1020,IsActive = true);
            lstPricebookEntryToInsert.add(pbe);
            
            Insert lstPricebookEntryToInsert;
            
            for(Integer i = 0 ; i < count ; i++)
            {
                QuoteLineItem qli = new QuoteLineItem(Product2Id = lstProductToInsert[0].Id, QuoteId = qId, Quantity = 5, PricebookEntryId = lstPricebookEntryToInsert[0].Id, UnitPrice = 1020, SAPQuoteLineItem__c = true);
                quotesLineItemsList.add(qli);
            }
            if(doInsert)
            {
                insert quotesLineItemsList ;
            }
        }        
        return quotesLineItemsList ;
    }
	
	/**
    * ****************************************************************************
    * This methods is to create test data for Opportunity Line Item object
    * ****************************************************************************
    */
    public static List<OpportunityLineItem> createOppLineItems(Integer count, Boolean doInsert)
    {
        List<Opportunity> oppList = createOpportunities(count, true);
        List<OpportunityLineItem> oliList = new List<OpportunityLineItem>();
        System.runAs(createUser())
        {
            Product2 pro = new Product2(Name = 'Test Product', Family = 'Mobile');
            Insert pro;
            for(Integer i = 0 ; i < count ; i++)
            {
                OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = oppList[i].Id, Quantity = 1000, product2id = pro.id);
                oliList.add(oli);
            }
            if(doInsert)
            {
                insert oliList ;
            }
        }        
        return oliList ;
    }
    
    public static List<OpportunityLineItem> createOppLineItems(Integer count, Boolean doInsert, Id OppId)
    {
        List<OpportunityLineItem> oliList = new List<OpportunityLineItem>();
        System.runAs(createUser())
        {            
            Opportunity opp = [select id,Pricebook2Id from opportunity where id =: OppId];
            opp.Pricebook2Id = Test.getStandardPricebookId();
            update opp;
        	Product2 pro = [select id from product2 where name = 'Test Product'];
            PricebookEntry pbe = new PricebookEntry(Pricebook2Id = Test.getStandardPricebookId(),Product2Id = pro.Id,UnitPrice = 1020,IsActive = true);
            Insert pbe;
            for(Integer i = 0 ; i < count ; i++)
            {
                OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = OppId, Quantity = 1000,  product2id = pro.id);
                oliList.add(oli);
            }
            if(doInsert)
            {
                insert oliList ;
            }
        }        
        return oliList ;
    }
    
    /**
    * ****************************************************************************
    * This methods is to create test data for PriceBook Automation object
    * ****************************************************************************
    */
    public static List<Price_Book_Automation__c> createPriceBookAutomation(Integer count, Boolean doInsert)
    {
        //Pricebook2 pbook = Test.getStandardPricebookId();
        List<Price_Book_Automation__c> pbaList = new List<Price_Book_Automation__c>();
        System.runAs(createUser())
        {
            for(Integer i = 0 ; i < count ; i++)
            {
                Price_Book_Automation__c pba = new Price_Book_Automation__c(Channel__c = 'System Integrator', Market__c = 'Cannabis', Partner_Status__c = 'Signed', Price_Book__c = Test.getStandardPricebookId(), Region__c = 'APAC', Key__c = 'PBA '+i, currencyisocode = 'USD');
                pbaList.add(pba);
            }
            if(doInsert)
            {
                Database.DMLOptions dml = new Database.DMLOptions(); 
 				dml.DuplicateRuleHeader.allowSave = true;
                Database.insert( pbaList, dml) ;
            }
        }        
        return pbaList ;
    }
    
    /**
    * ****************************************************************************
    * This methods is to create test data for Product Discount object
    * ****************************************************************************
    */
    public static List<Product_Discount__c> createProductDiscount(Integer count, Boolean doInsert)
    {
        //Pricebook2 pbook = Test.getStandardPricebookId();
        Product2 pro = new Product2(Name = 'Test Product', Family = 'Mobile');
        Insert pro;
        List<Product_Discount__c> pdList = new List<Product_Discount__c>();
        System.runAs(createUser())
        {
            for(Integer i = 0 ; i < count ; i++)
            {
                Product_Discount__c pd = new Product_Discount__c(Product__c = pro.id, Price_Book__c = Test.getStandardPricebookId(), Key__c = 'Product Discount '+i, First_Range__c = 250, First_Range_Value__c = 6000, Second_Range__c = 499, Second_Range_Value__c = 5000, Third_Range__c = 999, Third_Range_Value__c	= 4000, Fourth_Range__c = 1499, Fourth_Range_Value__c = 3000, Fifth_Range__c = 1999, Fifth_Range_Value__c = 2000, Sixth_Range_Value__c = 1000);
                pdList.add(pd);
            }
            if(doInsert)
            {
                insert pdList ;
            }
        }        
        return pdList ;
    }
    
     /**
    * ****************************************************************************
    * This methods is to create test data for Pricebook2 object
    * ****************************************************************************
    */
    public static List<PriceBook2> createPricebooks (integer count, Boolean doInsert)
    {
        List<PriceBook2> priceBookList = new List<PriceBook2>();
        for(integer i=0 ; i < count ; i++)
        {
            PriceBook2 pb2=new PriceBook2();
            pb2.Name = 'test' + i;
            pb2.IsActive = true;
            pb2.CurrencyIsoCode='USD';
            priceBookList.add(pb2);
        }
        if(doInsert)
        {
            insert priceBookList;
        }
        return priceBookList;
    }
    
     /**
    * ****************************************************************************
    * This methods is to create test data for SPAM_Email__c object
    * ****************************************************************************
    */
    public static List<SPAM_Email__c> createSPAMEmailRecords (integer count, Boolean doInsert)
    {
        List<SPAM_Email__c> spamEmailList = new List<SPAM_Email__c>();
        for(integer i=0 ; i < count ; i++)
        {
            SPAM_Email__c spemail = new SPAM_Email__c();
            spemail.Email_ID__c = 'contact'+i+'@abc.com';
            spemail.Sources_to_Block__c = 'Email;Email To Case;Web;Phone';
            spamEmailList.add(spemail);
        }
        if(doInsert)
        {
            insert spamEmailList;
        }
        return spamEmailList;
    }
}