force-app/main/default/objects/Account/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Account Channel</description>
    <label>Channel</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Account Market</description>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Partner_Status__c.field-meta.xml
<CustomField>
    <fullName>Partner_Status__c</fullName>
    <label>Partner Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Channel__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Partner_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Account Region</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Reseller.recordType-meta.xml
<RecordType>
    <fullName>Reseller</fullName>
    <active>true</active>
    <label>Reseller</label>
</RecordType>

force-app/main/default/objects/Bypass_Configuration__c/Bypass_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Bypass Configuration</label>
</CustomObject>

force-app/main/default/objects/Bypass_Configuration__c/fields/Opportunity_Process__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Process__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Opportunity Process</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reseller__c.field-meta.xml
<CustomField>
    <fullName>Reseller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reseller</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Reseller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reseller Opportunities</relationshipLabel>
    <relationshipName>ResellerOpportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price_Book_Automation__c/Price_Book_Automation__c.object-meta.xml
<CustomObject>
    <label>Price Book Automation</label>
    <nameField>
        <displayFormat>Auto-{00000}</displayFormat>
        <label>Automation Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Book Automations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_Book_Automation__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price_Book_Automation__c/fields/Partner_Status__c.field-meta.xml
<CustomField>
    <fullName>Partner_Status__c</fullName>
    <label>Partner Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Partner_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price_Book_Automation__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipName>Pricebooks_Automation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price_Book_Automation__c/fields/Reseller__c.field-meta.xml
<CustomField>
    <fullName>Reseller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reseller</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Reseller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Price Book Automations</relationshipLabel>
    <relationshipName>Price_Book_Automations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Channel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Web - Update</fullName>
    </customValue>
    <customValue>
        <fullName>OEM</fullName>
        <isActive>false</isActive>
        <label>OEM</label>
    </customValue>
    <customValue>
        <fullName>Wholesaler/Distributor</fullName>
        <isActive>false</isActive>
        <label>Wholesaler/Distributor</label>
    </customValue>
    <customValue>
        <fullName>PAR</fullName>
        <isActive>false</isActive>
        <label>PAR</label>
    </customValue>
    <customValue>
        <fullName>OSI</fullName>
        <isActive>false</isActive>
        <label>OSI</label>
    </customValue>
    <customValue>
        <fullName>OSGE</fullName>
        <isActive>false</isActive>
        <label>OSGE</label>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
        <isActive>false</isActive>
        <label>AR</label>
    </customValue>
    <customValue>
        <fullName>OSCH</fullName>
        <isActive>false</isActive>
        <label>OSCH</label>
    </customValue>
    <customValue>
        <fullName>Internal</fullName>
        <isActive>false</isActive>
        <label>Internal</label>
    </customValue>
    <customValue>
        <fullName>Business Development</fullName>
        <isActive>false</isActive>
        <label>Business Development</label>
    </customValue>
    <customValue>
        <fullName>Research</fullName>
        <isActive>false</isActive>
        <label>Research</label>
    </customValue>
    <customValue>
        <fullName>OSME</fullName>
        <isActive>false</isActive>
        <label>OSME</label>
    </customValue>
    <customValue>
        <fullName>System Integrator</fullName>
        <isActive>false</isActive>
        <label>Systems Integrator</label>
    </customValue>
    <customValue>
        <fullName>Ecomm</fullName>
        <isActive>false</isActive>
        <label>E-commerce</label>
    </customValue>
    <masterLabel>Channel</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Market.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Academia</fullName>
    </customValue>
    <customValue>
        <fullName>Cannabis</fullName>
    </customValue>
    <customValue>
        <fullName>Ornamental</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Produce</fullName>
    </customValue>
    <customValue>
        <fullName>Research</fullName>
    </customValue>
    <customValue>
        <fullName>OSGE</fullName>
        <isActive>false</isActive>
        <label>OSGE</label>
    </customValue>
    <customValue>
        <fullName>OSCH</fullName>
        <isActive>false</isActive>
        <label>OSCH</label>
    </customValue>
    <customValue>
        <fullName>Hemp</fullName>
        <isActive>false</isActive>
        <label>Hemp</label>
    </customValue>
    <customValue>
        <fullName>OSI</fullName>
        <isActive>false</isActive>
        <label>OSI</label>
    </customValue>
    <customValue>
        <fullName>Ecommerce</fullName>
        <isActive>false</isActive>
        <label>Ecommerce</label>
    </customValue>
    <customValue>
        <fullName>Authorized Reseller</fullName>
        <isActive>false</isActive>
        <label>Authorized Reseller</label>
    </customValue>
    <customValue>
        <fullName>Comm Ag - Ornamental</fullName>
        <isActive>false</isActive>
        <label>Comm Ag - Ornamental</label>
    </customValue>
    <customValue>
        <fullName>Comm Ag - Produce</fullName>
        <isActive>false</isActive>
        <label>Comm Ag - Produce</label>
    </customValue>
    <customValue>
        <fullName>OSME</fullName>
        <isActive>false</isActive>
        <label>OSME</label>
    </customValue>
    <masterLabel>Market</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Partner_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Signed</fullName>
    </customValue>
    <customValue>
        <fullName>Unsigned</fullName>
    </customValue>
    <masterLabel>Partner Status</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Region.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Americas-NA</fullName>
    </customValue>
    <customValue>
        <fullName>Americas-LATAM</fullName>
    </customValue>
    <customValue>
        <fullName>APAC</fullName>
    </customValue>
    <customValue>
        <fullName>EMEA</fullName>
    </customValue>
    <masterLabel>Region</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestOpportunityLineItemTrigger.cls
/**
*	@Author: Vartika Rai
*	@Company: HCL Technologies
*	@Class: TestOpportunityLineItemTrigger class
*	@Comments: consists of methods to test OpportunityTrigger, OpportunityTriggerHandler, OpportunityLineItemTrigger and OpportunityLineItemTrigger methods
*	@Created Date: 07/27/2021
*	@Version: 0.0
*
*	------------------------------------------------------------------------------------------
*	Modification Log:
*	==========================================================================================
*	@Version		@Author			@Date			@Reason
*	1.0             Lucas Silva     10-11-2023      Insert Bypass_Configuration__c in testhandlerMethods()
*	==========================================================================================
*/
@isTest
public class TestOpportunityLineItemTrigger {

      @testSetUp
    public static void setUpTestData()
    {
       List<Account> accList = TestDataFactory.createAccounts(2, true);
        accList[0].RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Reseller').getRecordTypeId();
        update accList;
        List<PriceBook2> pricebook = TestDataFactory.createPricebooks(1,true);
        List<Price_Book_Automation__c> pbaList = TestDataFactory.createPriceBookAutomation (2, true);
        pbaList[1].Price_Book__c = pricebook[0].id;
        pbaList[1].Reseller__c = accList[0].Id;
        pbaList[1].Market__c = '';
        pbaList[1].Region__c = '';   
        pbaList[1].Channel__c = '';   
        pbaList[1].Partner_Status__c = '';   
        update pbaList[1];
        TestDataFactory.createProductDiscount (1, true);        
        List<Opportunity> oppList = TestDataFactory.createOpportunities(1, true, accList[1].Id);
        List<Opportunity> oppWithResellersList = TestDataFactory.createOpportunitiesWithResellers (1, true, accList[1].Id, accList[0].Id);
    }
    
    @isTest
    public static void testhandlerMethods()
    {        
        System.runAs(TestDataFactory.createUser())
        {
            Opportunity opp = [Select id from Opportunity limit 1];
            Test.startTest();
            //Create ByPass record to bypass unnecessary processes
            Bypass_Configuration__c bypassConfiguration = new Bypass_Configuration__c();
            bypassConfiguration.Opportunity_Process__c = true;
            bypassConfiguration.SetupOwnerId = UserInfo.getUserId();
        	insert bypassConfiguration;
            
            List<OpportunityLineItem> oppLineItemList = TestDataFactory.createOppLineItems(1, true,opp.Id);
            oppLineItemList[0].quantity = 650;
            update oppLineItemList[0];
            oppLineItemList[0].quantity = 1500;
            update oppLineItemList[0];
            oppLineItemList[0].quantity = 100;
            update oppLineItemList[0];
            oppLineItemList[0].quantity = 2000;
            update oppLineItemList[0];
            oppLineItemList[0].quantity = 310;
            update oppLineItemList[0];
            Test.stopTest();
        }        
    }

}