force-app/main/default/objects/Price_Book_Automation__c/Price_Book_Automation__c.object-meta.xml
<CustomObject>
    <label>Price Book Automation</label>
    <nameField>
        <displayFormat>Auto-{00000}</displayFormat>
        <label>Automation Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Book Automations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Price_Book_Automation__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price_Book_Automation__c/fields/Partner_Status__c.field-meta.xml
<CustomField>
    <fullName>Partner_Status__c</fullName>
    <label>Partner Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Partner_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Price_Book_Automation__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipName>Pricebooks_Automation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Price_Book_Automation__c/fields/Reseller__c.field-meta.xml
<CustomField>
    <fullName>Reseller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reseller</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Reseller</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Price Book Automations</relationshipLabel>
    <relationshipName>Price_Book_Automations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Channel.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Web - Update</fullName>
    </customValue>
    <customValue>
        <fullName>OEM</fullName>
        <isActive>false</isActive>
        <label>OEM</label>
    </customValue>
    <customValue>
        <fullName>Wholesaler/Distributor</fullName>
        <isActive>false</isActive>
        <label>Wholesaler/Distributor</label>
    </customValue>
    <customValue>
        <fullName>PAR</fullName>
        <isActive>false</isActive>
        <label>PAR</label>
    </customValue>
    <customValue>
        <fullName>OSI</fullName>
        <isActive>false</isActive>
        <label>OSI</label>
    </customValue>
    <customValue>
        <fullName>OSGE</fullName>
        <isActive>false</isActive>
        <label>OSGE</label>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
        <isActive>false</isActive>
        <label>AR</label>
    </customValue>
    <customValue>
        <fullName>OSCH</fullName>
        <isActive>false</isActive>
        <label>OSCH</label>
    </customValue>
    <customValue>
        <fullName>Internal</fullName>
        <isActive>false</isActive>
        <label>Internal</label>
    </customValue>
    <customValue>
        <fullName>Business Development</fullName>
        <isActive>false</isActive>
        <label>Business Development</label>
    </customValue>
    <customValue>
        <fullName>Research</fullName>
        <isActive>false</isActive>
        <label>Research</label>
    </customValue>
    <customValue>
        <fullName>OSME</fullName>
        <isActive>false</isActive>
        <label>OSME</label>
    </customValue>
    <customValue>
        <fullName>System Integrator</fullName>
        <isActive>false</isActive>
        <label>Systems Integrator</label>
    </customValue>
    <customValue>
        <fullName>Ecomm</fullName>
        <isActive>false</isActive>
        <label>E-commerce</label>
    </customValue>
    <masterLabel>Channel</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Partner_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Signed</fullName>
    </customValue>
    <customValue>
        <fullName>Unsigned</fullName>
    </customValue>
    <masterLabel>Partner Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PricebookAutomationDAO.cls
public class PricebookAutomationDAO {
    private static final PricebookAutomationDAO instance = new PricebookAutomationDAO();    
    private PricebookAutomationDAO(){}
    
    public static PricebookAutomationDAO getInstance() {
        return instance;
    }
    /*---------------------------------------------------------------------------------------------------------------------------
* Author: Allan Pecli
* Method Description: Retrieve the Price Book Automation Map with ID = Product__c + Price_Book__c + CurrencyIsoCode
* CreatedDate: July 27, 2021
* Modification Comments:
-----------------------------------------------------------------------------------------------------------------------------*/
    public Map<String,Price_Book_Automation__c> getPricebookAutomationMapInfobyParameters(Set<Id> resellerIDs, Set<String> channelValues, Set<String> regionValues, Set<String> marketValues, Set<String> partnerStatusValues, Set<String> currencyIsoCodes)
    {
        Map<String,Price_Book_Automation__c> mapPricebookAutomation = new Map<String,Price_Book_Automation__c>();
        for(Price_Book_Automation__c pricebookAutomation : [SELECT Id, Reseller__c, Channel__c, Region__c, Market__c, Price_Book__c, Partner_Status__c, CurrencyIsoCode FROM Price_Book_Automation__c WHERE  (Reseller__c IN : resellerIDs) OR ( Channel__c IN:channelValues AND Region__c IN:regionValues AND Market__c IN:marketValues AND Partner_Status__c IN:partnerStatusValues AND CurrencyIsoCode IN:currencyIsoCodes)  ]){
            if( pricebookAutomation.Reseller__c != null)
            {
                mapPricebookAutomation.put(String.valueOf(pricebookAutomation.Reseller__c),pricebookAutomation);
            }
            else
            {
                mapPricebookAutomation.put(String.valueOf(pricebookAutomation.Channel__c) + String.valueOf(pricebookAutomation.Region__c) + String.valueOf(pricebookAutomation.Market__c) + String.valueOf(pricebookAutomation.Partner_Status__c) + pricebookAutomation.CurrencyIsoCode,pricebookAutomation);
            }            
        }
        if(!mapPricebookAutomation.IsEmpty()){
            return mapPricebookAutomation;
        }else{
            return new Map<String,Price_Book_Automation__c>();
        }
    }
}